# Generated by Django 5.2.4 on 2025-08-08 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Deleted')], default=0),
        ),
    ]
