# Generated by Django 5.2.4 on 2025-08-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_created_by_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='meta_title',
        ),
    ]
