# Generated by Django 5.2.4 on 2025-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blogcomment_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=0),
        ),
    ]
