# Generated by Django 5.2.4 on 2025-08-09 04:48

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blog_status_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tiktok',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_file',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jgp', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_profile',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='Ex: Software Engineer', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='x',
            field=models.URLField(blank=True, help_text='Twitter link', max_length=2000, null=True),
        ),
    ]
