# Generated by Django 5.2.4 on 2025-08-09 13:56

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_avatar_assistantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantlog',
            name='test_output',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
