# Generated by Django 5.2.4 on 2025-08-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_assistantlog_test_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
    ]
