# Generated by Django 5.2.4 on 2025-08-10 04:05

import django.core.validators
import django.db.models.deletion
import tinymce.models
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blog_total_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('hash_name', models.CharField(blank=True, max_length=31, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postreact',
            name='user',
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('feed', 'Feed'), ('academic', 'Academic')], db_index=True, default='feed', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=0)),
                ('total_comment', models.IntegerField(default=0)),
                ('total_view', models.IntegerField(default=0)),
                ('total_react', models.IntegerField(default=0)),
                ('banner', models.FileField(blank=True, null=True, upload_to='feed/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])])),
                ('pid', models.CharField(default=utils.utils.gen_hex, max_length=32, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'Feed',
                'db_table': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feed Comment',
                'db_table': 'feed_comment',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostReact',
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['type', 'status', '-created_at'], name='feeds_type_60b6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['status', '-created_at'], name='feeds_status_907ce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'academic'), _negated=True), ('content__isnull', False), _connector='OR'), name='content_required_for_academic_not_null'),
        ),
        migrations.AddConstraint(
            model_name='feed',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False)), fields=('slug',), name='unique_slug_when_present'),
        ),
    ]
