# Generated by Django 5.2.4 on 2025-08-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tag_remove_blogcomment_blog_remove_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='has_detail',
            field=models.BooleanField(default=False),
        ),
    ]
