# Generated by Django 5.2.4 on 2025-08-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tag_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='has_detail',
        ),
        migrations.AddField(
            model_name='feed',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hash_name',
            field=models.CharField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
