# Generated by Django 5.2.4 on 2025-08-11 02:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_feed_has_detail_feed_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='time_reader',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(help_text='Category must be publish status', limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='For academic type, content must not be empty; if empty, the feed will be saved as Draft.', null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='tags',
            field=models.ManyToManyField(help_text='Max 5 tags. If more, extra tags will be truncated.', to='core.tag'),
        ),
    ]
