# Generated by Django 5.2.4 on 2025-08-11 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='game/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='game/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
    ]
