# Generated by Django 5.2.4 on 2025-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_game_banner_alter_game_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Deleted')], default=1),
        ),
    ]
