# Generated by Django 5.2.4 on 2025-08-11 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'like'), (2, 'heart')])),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_reaction',
                'indexes': [models.Index(fields=['feed', 'type'], name='feed_reacti_feed_id_8c2382_idx'), models.Index(fields=['user'], name='feed_reacti_user_id_d42a91_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'feed'), name='uniq_user_feed_reaction')],
            },
        ),
    ]
